---

- name: Create Docker logs Ops Agent YAML file
  template:
    src: docker_ops_agent.yaml.j2
    dest: /tmp/docker_ops_agent.yaml
  delegate_to: localhost

- name: Add GCP Ops Agent on hosts
  include_role:
    name: google-cloud-ops-agents-ansible
  vars:
    agent_type: ops-agent
    main_config_file: /tmp/docker_ops_agent.yaml

- name: Clean up Docker logs Ops Agent YAML file
  file:
    path: /tmp/docker_ops_agent.yaml
    state: absent
  delegate_to: localhost
