---

- name: Create MariaDB Ops Agent YAML file
  template:
    src: mariadb_ops_agent.yaml.j2
    dest: /tmp/mariadb_ops_agent.yaml
  delegate_to: localhost

- name: Add GCP MariaDB Ops Agent
  include_role:
    name: google-cloud-ops-agents-ansible
  vars:
    agent_type: ops-agent
    main_config_file: /tmp/mariadb_ops_agent.yaml

- name: Clean up MariaDB Ops Agent YAML file
  file:
    path: /tmp/mariadb_ops_agent.yaml
    state: absent
  delegate_to: localhost
