---

- name: Create OpenSearch Ops Agent YAML file
  template:
    src: opensearch_ops_agent.yaml.j2
    dest: /tmp/opensearch_ops_agent.yaml
  delegate_to: localhost

- name: Add GCP OpenSearch Ops Agent
  include_role:
    name: google-cloud-ops-agents-ansible
  vars:
    agent_type: ops-agent
    main_config_file: /tmp/opensearch_ops_agent.yaml

- name: Clean up OpenSearch Ops Agent YAML file
  file:
    path: /tmp/opensearch_ops_agent.yaml
    state: absent
  delegate_to: localhost
