---

- name: Create Redis Ops Agent YAML file
  template:
    src: redis_ops_agent.yaml.j2
    dest: /tmp/redis_ops_agent.yaml
  delegate_to: localhost

- name: Add GCP Redis Ops Agent
  include_role:
    name: google-cloud-ops-agents-ansible
  vars:
    agent_type: ops-agent
    main_config_file: /tmp/redis_ops_agent.yaml

- name: Clean up Redis Ops Agent YAML file
  file:
    path: /tmp/redis_ops_agent.yaml
    state: absent
  delegate_to: localhost
