---
# NGINX image and container
nginx_docker_image: nginx
nginx_version: stable
nginx_docker_container: nginx

# NGINX node configuration
nginx_workdir: "/docker/nginx"
nginx_virtualhosts_workdir: "{{ nginx_workdir }}/conf"
nginx_log_dir: "{{ nginx_workdir }}/log"

# Create your instances configurations
## instances:
## - project: example
##   tenant: example
##   public: false
##   sortinghat:
##     tenant: example
##     dedicated_queue: true
##     openinfra_client_id: ""
##     openinfra_client_secret: ""
##   nginx:
##     fqdn: example.com
##     http_rest_api: true
## - project: example-public
##   tenant: example-public
##   public: true
##   sortinghat:
##     tenant: example-public
##     dedicated_queue: false
##   nginx:
##     fqdn: example-public.com
##     http_rest_api: false

# Service hosts
opensearch_endpoint: "https://{{ ansible_default_ipv4.address | list if 'all_in_one' in groups else  hostvars[(groups['opensearch'][0])].ansible_default_ipv4.address }}:9200"
sortinghat_host: "{{ ansible_default_ipv4.address if 'all_in_one' in groups else  hostvars[(groups['sortinghat'][0])].ansible_default_ipv4.address }}:9314"

# Certificates configuration
## Let's Encrypt configuration
nginx_letsencrypt_workdir: "{{ nginx_workdir }}/letsencrypt"
nginx_letsencrypt_logsdir: "{{ nginx_letsencrypt_workdir }}/logs"
nginx_letsencrypt_configdir: "{{ nginx_letsencrypt_workdir }}/config"
nginx_letsencrypt_webroot_path: "{{ nginx_letsencrypt_workdir }}/webroot"
nginx_letsencrypt_cert_warning_days: 30
nginx_letsencrypt_certbot_renew_script_dest: "{{ nginx_letsencrypt_workdir }}/certbot_renew.sh"
nginx_letsencrypt_cronjob_time: "daily" # "annually", "daily", "hourly", "monthly", "reboot", "weekly", "yearly"

## Custom certifications
nginx_certs_dir: "{{ nginx_workdir }}/certs"

## Uncomment to define custom certificates. Otherwise Let's Encrypt
## certificates will be used.
# custom_cert:
#   cert: foo/cert.crt
#   key: foo/cert.key

# NGINX proxy buffer settings
nginx_proxy_buffer_size: "128k"
nginx_proxy_buffer_size_per_conn: "256k"
nginx_proxy_total_buffers: 4
nginx_proxy_busy_buffers_size: "256k"

# GCS bucket access
## GCS directories
nginx_gcs_workdir: /docker/nginx/gcs
nginx_keys_workdir: /docker/nginx/keys

## Gcloud repository
gcloud_apt_deb_ubuntu_repository: >-
  deb [signed-by=/usr/share/keyrings/cloud.google.gpg]
  https://packages.cloud.google.com/apt cloud-sdk main

docker_network_name: bap_network
