---
# NGINX image and container
nginx_docker_image: nginx
nginx_version: stable
nginx_docker_container: nginx

# NGINX node configuration
nginx_workdir: "/docker/nginx"
nginx_virtualhosts_workdir: "{{ nginx_workdir }}/conf"
nginx_log_dir: "{{ nginx_workdir }}/log"

# Create your Nginx virtual host configurations
## nginx_virtualhosts:
##  - fqdn: example.com
##    public: false
##    tenant: example
##  - fqdn: example-public.com
##    public: true
##    tenant: example-public

# Service hosts
opensearch_endpoint: "https://{{ hostvars[(groups['opensearch'][0])].ansible_default_ipv4.address }}:9200"
sortinghat_host: "{{ hostvars[(groups['sortinghat'][0])].ansible_default_ipv4.address }}:9314"

# Certificates configuration

certs_dir: "{{ nginx_workdir }}/certs"

## Uncomment to define custom certificates. Otherwise self-signed
## certificates will be used.
# custom_cert:
#   cert: foo/cert.crt
#   key: foo/cert.key

# NGINX proxy buffer settings
nginx_proxy_buffer_size: "128k"
nginx_proxy_buffer_size_per_conn: "256k"
nginx_proxy_total_buffers: 4
nginx_proxy_busy_buffers_size: "256k"

# GCS bucket access
## GCS directories
nginx_gcs_workdir: /docker/nginx/gcs
nginx_keys_workdir: /docker/nginx/keys

## Gcloud repository
gcloud_apt_deb_ubuntu_repository: >-
  deb [signed-by=/usr/share/keyrings/cloud.google.gpg]
  https://packages.cloud.google.com/apt cloud-sdk main

