---
- name: Download OpenSearch Security backup from GCP bucket
  command: >
    gsutil cp -P gs://{{ backups_assets_bucket }}/opensearch-security-backup/{{ opensearch_security_backup_restore_name }}
    {{ opensearch_security_dir }}/{{ opensearch_security_backup_restore_name }}

- name: Empty OpenSearch Security backup directory
  shell: rm -rf {{ opensearch_security_backup_dir }}/*

- name: Unarchive OpenSearch Security backup file (.tgz)
  unarchive:
    src: "{{ opensearch_security_dir }}/{{ opensearch_security_backup_restore_name }}"
    dest: "{{ opensearch_security_backup_dir }}"
    extra_opts:
    - --transform
    - s/security_tenants/tenants/
    remote_src: yes

- name: Rename OpenSearch Security files removing date
  shell: >
    find {{ opensearch_security_backup_dir }}/ -regextype sed
    -regex '.*/{{ item }}_[0-9]\{4\}-[a-zA-Z]\{3\}-[0-9]\{2\}_[0-9]\{2\}-[0-9]\{2\}-[0-9]\{2\}.yml'
    -exec mv '{}' {{ opensearch_security_backup_dir }}/{{ item }}.yml \;
  with_items:
  - action_groups
  - allowlist
  - audit
  - config
  - internal_users
  - nodes_dn
  - roles
  - roles_mapping
  - tenants
  - whitelist

- name: Run securityadmin.sh to restore OpenSearch Security files
  command: >
    docker exec {{ opensearch_docker_container }}
    bash plugins/opensearch-security/tools/securityadmin.sh
    -cd /tmp/backup/
    -cacert config/{{ certs_files.ca_cert }}
    -cert config/{{ certs_files.admin_cert }}
    -key config/{{ certs_files.admin_key }}
    -icl -nhnv
  register: securityadmin_restore
  changed_when: false
  until: securityadmin.rc == 0
  retries: 10
  delay: 10
  any_errors_fatal: true
  run_once: true

- name: Show securityadmin_restore output
  debug:
    msg: "{{ securityadmin_restore.stdout }}"
  run_once: true

