- name: "Check if Slack Channel notification {{ item.config_id }} exists"
  uri:
    url: "{{ opensearch_snapshots_url }}/_plugins/_notifications/configs/{{ item.config_id }}"
    method: GET
    client_cert: "{{ certs_dir }}/{{ certs_files.admin_cert }}"
    client_key: "{{ certs_dir }}/{{ certs_files.admin_key }}"
    validate_certs: false
    status_code: 200, 404
  register: slack_channel_check

- name: "Create Channel notification {{ item.config_id }}"
  uri:
    url: "{{ opensearch_snapshots_url }}/_plugins/_notifications/configs"
    method: POST
    body_format: json
    body:
      config_id: "{{ item.config_id }}"
      name: "{{ item.name }}"
      config:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        config_type: "slack"
        is_enabled: true
        slack:
          url: "{{ item.slack_url }}"
    client_cert: "{{ certs_dir }}/{{ certs_files.admin_cert }}"
    client_key: "{{ certs_dir }}/{{ certs_files.admin_key }}"
    validate_certs: false
  when: slack_channel_check is not defined or slack_channel_check.status != 200

- name: "Update Channel notification {{ item.config_id }}"
  uri:
    url: "{{ opensearch_snapshots_url }}/_plugins/_notifications/configs/{{ item.config_id }}"
    method: PUT
    body_format: json
    body:
      config:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        config_type: "slack"
        is_enabled: true
        slack:
          url: "{{ item.slack_url }}"
    client_cert: "{{ certs_dir }}/{{ certs_files.admin_cert }}"
    client_key: "{{ certs_dir }}/{{ certs_files.admin_key }}"
    validate_certs: false
  when: slack_channel_check is defined and slack_channel_check.status == 200
