---

- name: Configure virtualhost(s)
  include_tasks: virtualhost.yml

- name: Remove old NGINX container
  docker_container:
    name: "{{ nginx_docker_container }}"
    state: absent

- name: Start NGINX container without SSL
  docker_container:
    name: "{{ nginx_docker_container }}"
    image: "{{ nginx_docker_image }}:{{ nginx_version }}"
    volumes:
      - "{{ nginx_virtualhosts_workdir}}:/etc/nginx/conf.d/"
    ports:
      - "80:80"    
    exposed_ports:
      - "80"
  when: enable_ssl|bool == false

- name: Start NGINX container enabling SSL
  docker_container:
    name: "{{ nginx_docker_container }}"
    image: "{{ nginx_docker_image }}:{{ nginx_version }}"
    volumes:
      - "{{ nginx_virtualhosts_workdir}}:/etc/nginx/conf.d/"
      - "{{ certs_dir }}/{{ ansible_hostname }}.crt:/etc/ssl/certs/{{ ansible_hostname }}.crt"
      - "{{ certs_dir }}/{{ ansible_hostname }}.key:/etc/ssl/private/{{ ansible_hostname }}.key"
    ports:
      - "80:80"
      - "443:443"
    exposed_ports:
      - "80"
      - "443"
  when: enable_ssl|bool == true
