---

- name: Install logrotate
  package:
    name: logrotate
    state: present

- name: Copy logrotate.conf to /etc/logrotate.conf
  copy:
    src: "{{ role_path }}/files/logrotate.conf"
    dest: /etc/logrotate.conf
    mode: "0644"

- name: Generate /etc/logrotate.d/nginx
  template:
    src: nginx_logrotate.j2
    dest: /etc/logrotate.d/nginx
    mode: "0644"

- name: Configure virtualhost(s)
  include_tasks: virtualhost.yml

- name: Create a network
  docker_network:
    name: "{{ docker_network_name }}"
  when: "'all_in_one' in groups"

- name: Remove old NGINX container
  docker_container:
    name: "{{ nginx_docker_container }}"
    state: absent

- name: Start NGINX container without SSL
  docker_container:
    name: "{{ nginx_docker_container }}"
    image: "{{ nginx_docker_image }}:{{ nginx_version }}"
    volumes:
      - "{{ nginx_virtualhosts_workdir}}:/etc/nginx/conf.d/"
    ports:
      - "80:80"    
    exposed_ports:
      - "80"
  when: enable_ssl|bool == false

- name: Start NGINX container enabling SSL
  docker_container:
    name: "{{ nginx_docker_container }}"
    image: "{{ nginx_docker_image }}:{{ nginx_version }}"
    volumes:
      - "{{ nginx_virtualhosts_workdir}}:/etc/nginx/conf.d/"
      - "{{ nginx_log_dir }}:/var/log/nginx"
      - "{{ certs_dir }}/{{ ansible_hostname }}.crt:/etc/ssl/certs/{{ ansible_hostname }}.crt"
      - "{{ certs_dir }}/{{ ansible_hostname }}.key:/etc/ssl/private/{{ ansible_hostname }}.key"
    ports:
      - "80:80"
      - "443:443"
    exposed_ports:
      - "80"
      - "443"
  when: enable_ssl|bool == true
