---
roles:
  - src: https://github.com/GoogleCloudPlatform/google-cloud-ops-agents-ansible
    version: 1.0.6

collections:
  - name: google.cloud
    version: 1.0.2
  - name: amazon.aws
    version: ">=8.0"
  - name: community.docker
    version: ">=5.0"
