---
- hosts: all_in_one
  roles:
    - mariadb
    - redis
    - opensearch
    - opensearch_dashboards
    #- sortinghat
    #- sortinghat_worker
    - grimoirelab
    - nginx
    - monitoring
  become: true
