---
- hosts: grimoirelab
  pre_tasks:
    - name: Gather facts from MariaDB nodes
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items:
        - "{{ groups['mariadb'] }}"
  roles:
    - grimoirelab
  become: true
