---
- hosts: all, !ungrouped, !redis, !nginx, !mariadb, !opensearch
  become: true
  tasks:
    - name: All hosts except Redis, NGINX, and MariaDB
      include_role:
        name: monitoring
        tasks_from: main

- hosts: nginx
  become: true
  tasks:
    - name: NGINX monitoring
      include_role:
        name: monitoring
        tasks_from: nginx

- hosts: redis
  become: true
  tasks:
    - name: Redis monitoring
      include_role:
        name: monitoring
        tasks_from: redis

- hosts: mariadb
  become: true
  tasks:
    - name: MariaDB monitoring
      include_role:
        name: monitoring
        tasks_from: mariadb

- hosts: opensearch
  become: true
  tasks:
    - name: OpenSearch monitoring
      include_role:
        name: monitoring
        tasks_from: opensearch
