---
- hosts: nginx
  pre_tasks:
    - name: Gather facts from other service nodes
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items:
        - "{{ groups['opensearch'] }}"
        - "{{ groups['opensearch_dashboards'] }}"
        - "{{ groups['opensearch_dashboards_anonymous'] }}"
        - "{{ groups['sortinghat'] }}"
  roles:
    - nginx
  become: true
