---
- hosts: nginx
  pre_tasks:
    - name: Gather facts from other service nodes
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items:
        - "{{ groups['opensearch'] }}"
        - "{{ groups['sortinghat'] }}"

    - name: Gather facts from opensearch_dashboards service
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      when: ('opensearch_dashboards' in groups) and (hostvars[item]['ansible_default_ipv4'] is not defined)
      with_items:
        - "{{ groups['opensearch_dashboards'] }}"

    - name: Gather facts from opensearch_dashboards_anonymous service
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      when: ('opensearch_dashboards_anonymous' in groups) and (hostvars[item]['ansible_default_ipv4'] is not defined)
      with_items:
        - "{{ groups['opensearch_dashboards_anonymous'] }}"
  roles:
    - nginx
  become: true
