- name: Install certbot
  pip:
    name:
      - certbot
      - certbot-nginx
    break_system_packages: true

- name: Register certbot
  run_once: true
  shell: |
    certbot -n register --agree-tos --email {{ letsencrypt_register_email }} --work-dir {{ nginx_letsencrypt_workdir }} --logs-dir {{ nginx_letsencrypt_logsdir }} --config-dir {{ nginx_letsencrypt_configdir }}
    touch {{ nginx_letsencrypt_workdir }}/.registered
  args:
    creates: "{{ nginx_letsencrypt_workdir }}/.registered"

- name: "Get {{ hostname }} certificate info"
  shell: openssl x509 -in "{{ nginx_letsencrypt_configdir }}/live/{{ hostname }}/cert.pem" -noout -dates | awk -F= '/notAfter=/ {print $2}'
  register: cert_info

- name: "Show {{ hostname }} certificate info"
  debug:
    msg: "{{ cert_info }}"

- name: "Create certificate for {{ hostname }}"
  command: "certbot -n certonly --webroot -w {{ nginx_letsencrypt_webroot_path }} -d {{ hostname }} --work-dir {{ nginx_letsencrypt_workdir }} --logs-dir {{ nginx_letsencrypt_logsdir }} --config-dir {{ nginx_letsencrypt_configdir }}"
  args:
    creates: "{{ nginx_letsencrypt_workdir }}/live/{{ hostname }}"
  ignore_errors: true
  when: cert_info.stderr

- name: Copy renew Cerbot script
  run_once: true
  template:
    src: certbot_renew.sh.j2
    dest: "{{ nginx_letsencrypt_certbot_renew_script_dest }}"
    mode: 0500
    owner: "{{ ansible_user_id }}"

- name: Setup cronjob for renewal (Let's Encrypt certificates expire in 90 days)
  run_once: true
  cron:
    name: Certbot renewal
    job: "{{ nginx_letsencrypt_certbot_renew_script_dest }}"
    special_time: "{{ nginx_letsencrypt_cronjob_time }}"
