---

- name: Add GPG key for gcloud repository
  shell: "curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -"

- name: Add gcloud repository (Debian/Ubuntu)
  apt_repository:
    repo: "{{ gcloud_apt_deb_ubuntu_repository }}"
    state: present
    update_cache: true
  when: ansible_distribution == "Debian"
    or ansible_distribution == "Ubuntu"

- name: Install gcloud package
  apt:
    name: google-cloud-cli
    state: present
    update_cache: true

- name: Create GCS folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    recurse: true
  with_items:
    - "{{ nginx_gcs_workdir }}"
    - "{{ nginx_keys_workdir }}"

- name: Copy GCP service account file
  copy:
    src: "{{ gcp_service_account_host_file }}"
    dest: "{{ nginx_keys_workdir }}/key.json"
    owner: '1000'
    group: '1000'
    mode: 0644

- name: Activate service account
  shell: gcloud auth activate-service-account --key-file "{{ nginx_keys_workdir }}/key.json"

