---

- name: Configure virtualhost(s)
  include_tasks: virtualhost.yml
  run_once: "{{ bap_single_host|bool }}"
  loop: "{{ nginx_virtualhosts }}"
  loop_control:
    loop_var: instance

- name: Configure NGINX status page
  template:
    src: status.conf.j2
    dest: "{{ nginx_virtualhosts_workdir }}/status.conf"

- name: Configure Google Cloud Storage (GCS)
  include_tasks: gcs.yml

- name: Configure NGINX proxy buffer sizes
  template:
    src: proxy_buffer.conf.j2
    dest: "{{ nginx_virtualhosts_workdir }}/proxy_buffer.conf"
    backup: true

- name: Remove old NGINX container
  docker_container:
    name: "{{ nginx_docker_container }}"
    state: absent

- name: Create docker volumes for certs and config
  set_fact:
    nginx_volumes: |-
      [
      {% for instance in nginx_virtualhosts %}
        "{{ certs_dir }}/{{ instance.fqdn }}.crt:/etc/ssl/certs/{{ instance.fqdn }}.crt",
        "{{ certs_dir }}/{{ instance.fqdn }}.key:/etc/ssl/private/{{ instance.fqdn }}.key",
      {% endfor %}
        "{{ nginx_virtualhosts_workdir}}:/etc/nginx/conf.d/",
        "{{ nginx_gcs_workdir }}:/opt/gcs",
        "{{ nginx_log_dir }}:/var/log/nginx"
      ]

- name: Check the list of volumes
  debug:
    msg: "{{ nginx_volumes }}"

- name: Start NGINX container
  docker_container:
    name: "{{ nginx_docker_container }}"
    image: "{{ nginx_docker_image }}:{{ nginx_version }}"
    volumes: "{{ nginx_volumes }}"
    ports:
      - "80:80"
      - "443:443"
    exposed_ports:
      - "80"
      - "443"

- name: Launch first rsync
  shell: gsutil -m rsync -d -r "gs://{{ sortinghat_assets_bucket }}/" "{{ nginx_gcs_workdir }}"
