---

- name: Create NGINX virtualhost(s) directory
  file:
    path: "{{ nginx_virtualhosts_workdir }}"
    state: directory
    mode: 0750
    recurse: true

- name: Create certificates directory
  file:
    path: "{{ certs_dir }}"
    state: directory
    mode: 0750
    recurse: true

- name: Create NGINX log directory
  file:
    path: "{{ nginx_log_dir }}"
    state: directory
    mode: 0755

- name: "Generate self-signed certificate for {{ instance.fqdn }}"
  shell: "./generate_cert.sh {{ instance.fqdn }}"
  become: false
  args:
    chdir: "{{ role_path }}/files"
    creates: "{{ role_path }}/files/cert.crt"
  delegate_to: localhost
  when: custom_cert is not defined

- name: "Copy SSL certificate for {{ instance.fqdn }}"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - src: "{{ custom_cert.cert if custom_cert is defined else 'cert.crt' }}"
      dest: "{{ certs_dir }}/{{ instance.fqdn }}.crt"
      owner: '1000'
      group: '1000'
      mode: '0644'
    - src: "{{ custom_cert.key if custom_cert is defined else 'cert.key' }}"
      dest: "{{ certs_dir }}/{{ instance.fqdn }}.key"
      owner: '1000'
      group: '1000'
      mode: '0600'
  loop_control:
    label: "{{ item.dest }}"

- name: "Create virtualhost configuration for {{ instance.fqdn }}"
  template:
    src: "{{ item.template }}"
    dest: "{{ nginx_virtualhosts_workdir }}/{{ item.name }}"
    backup: true
  with_items:
    - name: "{{ instance.fqdn }}.conf"
      template: vhost.j2
    - name: "{{ instance.fqdn }}_uwsgi_params"
      template: uwsgi_params.j2
