---

- name: Generate certificate using certbot
  include_tasks: certbot.yml
  vars:
    hostname: "{{ instance.nginx.fqdn }}"
  when: custom_cert is undefined

- name: "Copy custom SSL certificates"
  run_once: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - src: "{{ custom_cert.cert if custom_cert is defined else 'cert.crt' }}"
      dest: "{{ nginx_certs_dir }}/custom.crt"
      owner: '1000'
      group: '1000'
      mode: '0644'
    - src: "{{ custom_cert.key if custom_cert is defined else 'cert.key' }}"
      dest: "{{ nginx_certs_dir }}/custom.key"
      owner: '1000'
      group: '1000'
      mode: '0600'
  loop_control:
    label: "{{ item.dest }}"
  when: custom_cert is defined

- name: "Create load balancer configuration for OpenSearch nodes"
  run_once: true
  template:
    src: "opensearch_nodes.j2"
    dest: "{{ nginx_virtualhosts_workdir }}/opensearch_nodes.conf"
    backup: true
  when: instance.nginx.http_rest_api is defined and instance.nginx.http_rest_api

- name: "Create virtualhost configuration for {{ instance.nginx.fqdn }}"
  template:
    src: vhost.j2
    dest: "{{ nginx_virtualhosts_workdir }}/{{ instance.nginx.fqdn }}.conf"
    backup: true
