---

- name: Create a list of priviledges
  set_fact:
    priviledges: |-
      {
      {% for item in nginx_virtualhosts %}
        "{{ item.tenant }}.*":"ALL,GRANT",
      {% endfor %}
        "{{ sortinghat_database }}.*":"ALL,GRANT"
      }

- name: Check priviledges list
  debug:
    msg: "{{ priviledges }}"

- name: Create MariaDB service account for SortingHat worker
  mysql_user:
    name: "{{ mariadb_service_account }}"
    host: "{{ ansible_default_ipv4.address }}"
    password: "{{ mariadb_service_account_password }}"
    priv: "{{ priviledges }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_host: "{{ item }}"
    state: present
  register: result
  retries: 2
  delay: 5
  until: result is success
  with_items:
    - "{{ mariadb_hosts }}"

- name: Create SortingHat Worker directory
  file:
    path: "{{ sortinghat_worker_workdir }}"
    state: directory
    mode: 0750
    recurse: true

- name: "Create SortingHat multi tenant file"
  copy:
    mode: '0644'
    dest: "{{ sortinghat_multi_tenant_list_path }}"
    content: |-
      {
        "tenants": [
          {% for item in nginx_virtualhosts %}
            {{ "" if loop.first else "," }}
            "{{ item.tenant }}"
          {% endfor %}
        ]
      }

- name: Remove old SortingHat worker container
  docker_container:
    name: "{{ sortinghat_worker_docker_container }}-{{ item }}"
    state: absent
  with_sequence: start=1 end="{{ sortinghat_workers }}"

- name: Start SortingHat worker container
  docker_container:
    name: "{{ sortinghat_worker_docker_container }}-{{ item }}"
    image: "{{ sortinghat_worker_docker_image }}:{{ sortinghat_worker_version }}"
    pull: yes
    env:
      SORTINGHAT_CONFIG: sortinghat.config.settings
      SORTINGHAT_SECRET_KEY: "{{ sortinghat_secret_key }}"
      SORTINGHAT_DB_HOST: "{{ mariadb_hosts }}"
      SORTINGHAT_DB_USER: "{{ mariadb_service_account }}"
      SORTINGHAT_DB_PASSWORD: "{{ mariadb_service_account_password }}"
      SORTINGHAT_DB_DATABASE: "{{ sortinghat_database }}"
      SORTINGHAT_REDIS_HOST: "{{ redis_hosts }}"
      SORTINGHAT_REDIS_PASSWORD: "{{ redis_password }}"
      SORTINGHAT_REDIS_DB: "{{ redis_database }}"
      SORTINGHAT_OPENINFRA_CLIENT_ID: "{{ sortinghat_openinfra_client_id }}"
      SORTINGHAT_OPENINFRA_CLIENT_SECRET: "{{ sortinghat_openinfra_client_secret }}"
      SORTINGHAT_MULTI_TENANT: "{{ sortinghat_multi_tenant }}"
      SORTINGHAT_MULTI_TENANT_LIST_PATH: "{{ sortinghat_multi_tenant_list_path }}"
    volumes:
      - "{{ sortinghat_multi_tenant_list_path }}:{{ sortinghat_multi_tenant_list_path }}"
  with_sequence: start=1 end="{{ sortinghat_workers }}"
