---

- name: All in one host (MariaDB and Redis hosts)
  set_fact:
    mariadb_hosts: "{{ groups['all_in_one'][0] }}"
    redis_hosts: "{{ groups['all_in_one'][0] }}"
  when: "'all_in_one' in groups and inventory_hostname in groups['all_in_one']"

- name: "Create SortingHat tenants info"
  set_fact:
    tenants_info: |-
      [
      {% for item in instances %}
        {{ "" if loop.first else "," }}
        {
          "tenant": "{{ item.sortinghat.tenant | replace('-','_') }}",
          "dedicated_queue": {{ item.sortinghat.dedicated_queue | default(false) }},
          "openinfra_client_id": "{{ item.sortinghat.openinfra_client_id | default("") }}",
          "openinfra_client_secret": "{{ item.sortinghat.openinfra_client_secret | default("") }}"
        }
      {% endfor %}
      ]

- name: Filter out duplicated entries of tenants info
  set_fact:
    tenants: |-
      {{
        tenants_info
        | json_query('[].{
          "tenant": tenant,
          "dedicated_queue": dedicated_queue,
          "openinfra_client_id": openinfra_client_id,
          "openinfra_client_secret": openinfra_client_secret
          }')
       | unique
      }}

- name: Check multi-tenancy configuration
  assert:
    that:
      - "{{ tenants|length }} | int == 1"
    fail_msg: "Multi-tenancy is deactivated but multiple configurations were found."
  when:
    - sortinghat_multi_tenant is undefined or sortinghat_multi_tenant == "false"

- name: Create a list of databases
  set_fact:
    databases: |-
      [
      {% for item in tenants %}
        {{ "" if loop.first else "," }}
        "{{ item.tenant | replace('-','_') }}"
      {% endfor %}
      ]

- name: Check databases list
  debug:
    msg: "{{ databases }}"

- name: Create a list of privileges
  set_fact:
    privileges: |-
      {
      {% for item in databases %}
        "{{ item }}.*":"ALL,GRANT",
      {% endfor %}
        "{{ sortinghat_database | replace('-','_') }}.*":"ALL,GRANT"
      }

- name: Check privileges list
  debug:
    msg: "{{ privileges }}"

- name: Create MariaDB service account for SortingHat worker
  mysql_user:
    name: "{{ mariadb_service_account }}"
    host: "{{ '172.%' if 'all_in_one' in groups else ansible_all_ipv4_addresses }}"
    password: "{{ mariadb_service_account_password }}"
    priv: "{{ privileges }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_host: "{{ item }}"
    state: present
  register: result
  retries: 2
  delay: 5
  until: result is success
  with_items:
    - "{{ mariadb_hosts }}"

- name: Create SortingHat Worker directory
  file:
    path: "{{ sortinghat_worker_workdir }}"
    state: directory
    mode: 0750
    recurse: true

- name: "Create SortingHat multi-tenant file"
  copy:
    dest: "{{ sortinghat_multi_tenant_list_path }}"
    mode: 0644
    content: |-
      {
        "tenants": [
          {% for item in tenants %}
            {{ "" if loop.first else "," }}
            {
               "name": "{{ item.tenant }}",
               "dedicated_queue": {{ item.dedicated_queue }}
            }
          {% endfor %}
        ]
      }

- name: "Create a docker network: {{ docker_network_name }}"
  docker_network:
    name: "{{ docker_network_name }}"

- name: Remove old SortingHat worker container
  docker_container:
    name: "{{ sortinghat_worker_docker_container }}-{{ item }}"
    state: absent
  with_sequence: start=1 end="{{ sortinghat_workers }}"

- name: Start SortingHat worker container
  docker_container:
    name: "{{ sortinghat_worker_docker_container }}-{{ item }}"
    image: "{{ sortinghat_worker_docker_image }}:{{ sortinghat_worker_version }}"
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - "{{ sortinghat_worker_docker_container | replace('_','-') }}-{{ item }}"
    pull: yes
    env:
      SORTINGHAT_CONFIG: sortinghat.config.settings_bap
      SORTINGHAT_SECRET_KEY: "{{ sortinghat_secret_key }}"
      SORTINGHAT_DB_HOST: "{{ mariadb_hosts }}"
      SORTINGHAT_DB_USER: "{{ mariadb_service_account }}"
      SORTINGHAT_DB_PASSWORD: "{{ mariadb_service_account_password }}"
      SORTINGHAT_DB_DATABASE: "{{ sortinghat_database | replace('-','_') }}"
      SORTINGHAT_REDIS_HOST: "{{ redis_hosts }}"
      SORTINGHAT_REDIS_PASSWORD: "{{ redis_password }}"
      SORTINGHAT_REDIS_DB: "{{ redis_database }}"
      SORTINGHAT_MULTI_TENANT: "{{ sortinghat_multi_tenant }}"
      SORTINGHAT_MULTI_TENANT_LIST_PATH: "{{ sortinghat_multi_tenant_list_path }}"
    volumes:
      - "{{ sortinghat_multi_tenant_list_path }}:{{ sortinghat_multi_tenant_list_path }}"
  with_sequence: start=1 end="{{ sortinghat_workers }}"

- name: "Remove old SortingHat dedicated workers {{ item.tenant }}"
  docker_container:
    name: "{{ sortinghat_worker_docker_container }}-{{ item.tenant }}"
    state: absent
  loop: "{{ tenants }}"
  when:
    - sortinghat_multi_tenant is defined
    - sortinghat_multi_tenant == "true"
    - item.dedicated_queue is defined
    - item.dedicated_queue == true

- name: "Start SortingHat dedicated worker {{ item.tenant }}"
  docker_container:
    name: "{{ sortinghat_worker_docker_container }}-{{ item.tenant }}"
    image: "{{ sortinghat_worker_docker_image }}:{{ sortinghat_worker_version }}"
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - "{{ sortinghat_worker_docker_container | replace('_','-') }}-{{ item.tenant }}"
    pull: yes
    command: "{{ item.tenant }}"
    env:
      SORTINGHAT_CONFIG: sortinghat.config.settings_bap
      SORTINGHAT_SECRET_KEY: "{{ sortinghat_secret_key }}"
      SORTINGHAT_DB_HOST: "{{ mariadb_hosts }}"
      SORTINGHAT_DB_USER: "{{ mariadb_service_account }}"
      SORTINGHAT_DB_PASSWORD: "{{ mariadb_service_account_password }}"
      SORTINGHAT_DB_DATABASE: "{{ sortinghat_database | replace('-','_') }}"
      SORTINGHAT_REDIS_HOST: "{{ redis_hosts }}"
      SORTINGHAT_REDIS_PASSWORD: "{{ redis_password }}"
      SORTINGHAT_REDIS_DB: "{{ redis_database }}"
      SORTINGHAT_OPENINFRA_CLIENT_ID: "{{ item.openinfra_client_id }}"
      SORTINGHAT_OPENINFRA_CLIENT_SECRET: "{{ item.openinfra_client_secret }}"
      SORTINGHAT_MULTI_TENANT: "{{ sortinghat_multi_tenant }}"
      SORTINGHAT_MULTI_TENANT_LIST_PATH: "{{ sortinghat_multi_tenant_list_path }}"
    volumes:
      - "{{ sortinghat_multi_tenant_list_path }}:{{ sortinghat_multi_tenant_list_path }}"
  loop: "{{ tenants }}"
  when:
    - sortinghat_multi_tenant is defined
    - sortinghat_multi_tenant == "true"
    - item.dedicated_queue is defined
    - item.dedicated_queue == true
