---

- name: "Set {{ instance.project }} instance variables"
  set_fact:
    instance_dir: "{{ mordred_instances_dir }}/{{ instance.project }}"
  delegate_to: "{{ groups['mordred'][instance.mordred.host] }}"
  run_once: true

- name: "Ensure {{ instance.project }} instance directories are created"
  file:
    state: directory
    path: "{{ item }}"
    owner: grimoire
    group: grimoire
    mode: '0774'
  with_items:
    - "{{ instance_dir }}/conf"
    - "{{ instance_dir }}/logs"
    - "{{ instance_dir }}/sources"
    - "{{ instance_dir }}/perceval-cache"
  delegate_to: "{{ groups['mordred'][instance.mordred.host] }}"
  run_once: true

- name: "Add {{ instance.tenant }} tenant to aliases.json file"
  become: false
  command: >-
      python3 {{ role_path }}/files/add_tenant_aliases.py
      {{ upstream_aliases.dest }} {{ instance.tenant }} -o /tmp/{{ instance.tenant }}_aliases.json
  delegate_to: localhost
  changed_when: false
  run_once: true

- name: "Copy {{ instance.tenant }} aliases.json"
  copy:
    src: "/tmp/{{ instance.tenant }}_aliases.json"
    dest: "{{ instance_dir }}/conf/aliases.json"
    owner: grimoire
    group: grimoire
    mode: '0640'
  delegate_to: "{{ groups['mordred'][instance.mordred.host] }}"
  run_once: true

- name: "Checkout {{ instance.project }} sources repo"
  become: true
  become_user: grimoire
  git:
    repo: "{{ instance.mordred.sources_repository }}"
    dest: "{{ instance_dir }}/sources"
    force: true
  when: instance.mordred.sources_repository is defined
  delegate_to: "{{ groups['mordred'][instance.mordred.host] }}"
  run_once: true

- name: "Change {{ instance.project }} sources permissions"
  file:
    state: directory
    path: "{{ instance_dir }}/sources"
    owner: grimoire
    group: grimoire
    mode: '0774'
  delegate_to: "{{ groups['mordred'][instance.mordred.host] }}"
  run_once: true

- name: "Create cron job to pull changes from {{ instance.project }} sources repo"
  cron:
    name: "Pull {{ instance.project }} sources"
    user: "{{ ansible_user_id }}"
    job: "cd {{ instance_dir }}/sources && git pull"
  delegate_to: "{{ groups['mordred'][instance.mordred.host] }}"
  run_once: true

- name: "Create MariaDB service account for {{ instance.project }}"
  mysql_user:
    name: "{{ mariadb_service_account }}"
    host: "{{ ansible_default_ipv4.address }}"
    password: "{{ mariadb_service_account_password }}"
    priv: '*.*:ALL,GRANT'
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_host: "{{ item }}"
    state: present
  register: result
  retries: 2
  delay: 5
  until: result is success
  with_items:
    - "{{ mariadb_hosts }}"
  delegate_to: "{{ groups['mordred'][instance.mordred.host] }}"
  run_once: true

- name: Set anonymous role if opensearch_dashboards_anonymous is defined and the instance is public
  set_fact:
    anonymous: "{% if 'opensearch_dashboards_anonymous' in groups and groups['opensearch_dashboards_anonymous'] and instance.public %} -a {% else %} {% endif %}"
  delegate_to: "{{ groups['mordred'][instance.mordred.host] }}"
  run_once: true

- name: Add --force option (create_roles_tenat.py) if overwrite_roles is defined and the value is true
  set_fact:
    overwrite_roles: "{% if instance.overwrite_roles is defined and instance.overwrite_roles %} --force {% else %} {% endif %}"
  delegate_to: "{{ groups['mordred'][instance.mordred.host] }}"
  run_once: true

- name: "Create roles and tenant for {{ instance.project }}"
  become: false
  command: >-
    python3 {{ role_path }}/files/create_roles_tenant.py
    https://{{ opensearch_admin_user }}:{{ opensearch_admin_password }}@{{ groups['opensearch'][0] }}:9200 {{ instance.tenant }} {{ anonymous }}
    {{ overwrite_roles }}
  delegate_to: localhost
  run_once: true

- name: "Create mordred user for {{ instance.project }}"
  uri:
    url: "https://{{ groups['opensearch'][0] }}:9200/_plugins/_security/api/internalusers/{{ instance.tenant }}_mordred"
    url_username: "{{ opensearch_admin_user }}"
    url_password: "{{ opensearch_admin_password }}"
    force_basic_auth: yes
    method: PUT
    status_code: 200
    body_format: json
    body:
      opendistro_security_roles: ["bap_{{ instance.tenant }}_mordred_role"]
      password: "{{ instance.mordred.password }}"
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 10
  delay: 2
  become: false
  delegate_to: "{{ groups['mordred'][instance.mordred.host] }}"
  run_once: true
