---

- name: Create group grimoire
  group:
    name: grimoire
    state: present

- name: Create user grimoire
  user:
    name: grimoire
    groups: grimoire
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

- name: Configure Mordred
  import_tasks: configure.yml

- name: Remove old Mordred container(s)
  docker_container:
    name: "mordred_{{ item.project }}"
    state: absent
  with_items:
    - "{{ mordred_instances }}"

- name: docker
  docker_container:
    name: "mordred_{{ item.project }}"
    image: "{{ bap_docker_image }}:{{ bap_version }}"
    volumes:
    - "{{ mordred_ssh_dir }}:/home/grimoire/.ssh/"
    - "{{ mordred_setups_dir }}/{{ item.project }}/setup.cfg:/home/grimoire/conf/setup.cfg"
    - "{{ mordred_instances_dir }}/{{ item.project }}/conf/:/home/grimoire/conf/"
    - "{{ mordred_instances_dir }}/{{ item.project }}/sources/:/home/grimoire/data-sources/"
    - "{{ mordred_instances_dir }}/{{ item.project }}/logs/:/home/grimoire/logs/"
    - "{{ mordred_instances_dir }}/{{ item.project }}/perceval-cache/:/home/grimoire/.perceval/"
  with_items:
    - "{{ mordred_instances }}"
