---
# Python packages
python_packages:
  - boto>=2.9

# MariaDB

mariadb_docker_image: mariadb
mariadb_version: latest
mariadb_docker_container: mariadb

# Number of seconds the server waits for activity of a non-interactive
# connection before closing it. The default value is 28800 seconds (8 hours).
mariadb_wait_timeout: 28800

# Log all queries that have taken more than the number of seconds defined
# on this parameter.
mariadb_long_query_time: 30

mariadb_workdir: "/docker/mariadb"
mariadb_logs_dir: "{{ mariadb_workdir }}/log"
gcp_service_account_file: "{{ mariadb_workdir }}/gcs_credentials.json"

# Set in your environments vars.yml copying the name of the bucket created by terraform
#backups_assets_bucket: bap-mariadb-backups-<XXXXXXXX>.
#To create gs_access_key and gs_secret_key.
#1. https://console.cloud.google.com/storage
#2. Click on `bap-mariadb-backups-<XXXXXXXX>`
#3. Click on `Settings`
#4. Click on `INTEROPERABILITY`
#5. In `Access keys for service accounts` click on `CREATE A KEY FOR A SERVICE ACCOUNT`
#6. Select the account and click on `CREATE KEY`
#restore_mariadb_backup:
#  name: <BACKUP-SQL-NAME>
#  dest: "/tmp/mariadb.sql"
#  gs_access_key: <XXX>
#  gs_secret_key: <YYY>

## Crontab
mariadb_backup_cronjob: true
mariadb_backup_cronjob_time:
  hour: "6"
  minute: "0"
  weekday: "0"
mariadb_backup_script: /usr/local/bin/mariadb_backup.sh

# Improve MariaDB performance. A good value is 70%-80% of available memory.
# By default it use e2-standard-2 8G of memory. 6.4G is the 80% of 8G -> 6871947673
mariadb_innodb_buffer_pool_size: 6871947673

docker_network_name: bap_network
