---

- name: Add GPG key for gcloud repository
  shell: "curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -"

- name: Add gcloud repository (Debian/Ubuntu)
  apt_repository:
    repo: "{{ gcloud_apt_deb_ubuntu_repository }}"
    state: present
    update_cache: true
  when: ansible_distribution == "Debian"
    or ansible_distribution == "Ubuntu"

- name: Install gcloud package
  apt:
    name: google-cloud-cli
    state: present
    update_cache: true

- name: Create GCS folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    recurse: true
  with_items:
    - "{{ grimoirelab_gcs_workdir }}"
    - "{{ keys_dir }}"

- name: Copy GCP service account file
  copy:
    src: "{{ gcp_service_account_host_file }}"
    dest: "{{ gcp_service_account_file }}"
    mode: 0644

- name: Activate service account
  shell: gcloud auth activate-service-account --key-file "{{ gcp_service_account_file }}"

- name: Upload GrimoireLab static files to GCP Storage
  shell: gsutil cp -r "{{ grimoirelab_static_workdir }}" "gs://{{ sortinghat_assets_bucket }}/grimoirelab_core/"
  args:
    executable: /bin/bash
