---

# SortingHat image and container
sortinghat_docker_image: bitergia/bitergia-analytics-sortinghat
sortinghat_version: 0.7.0-rc1
sortinghat_docker_container: bap_sortinghat

# SortingHat node configuration
sortinghat_workdir: "/docker/sortinghat"
keys_dir:  "{{ sortinghat_workdir }}/keys"
gcp_service_account_file: "{{ keys_dir }}/credentials.json"

# SortingHat network
server_name: sortinghat
network:
  bind_host: 0.0.0.0
  publish_host: "{{ ansible_default_ipv4.address }}"

# Nginx virtual hosts
nginx_virtualhosts:
  - fqdn: example.com
  - fqdn: example2.com

# Database
sortinghat_database: sortinghat_db
mariadb_hosts: "{{ groups['mariadb'] | first }}"
redis_database: "0"
redis_hosts: "{{ groups['redis'] | first }}"


# Debug mode (on: 'true', '1'; off: 'false', '0')
sortinghat_debug: "false"

# CSRF and CORS configuration
sortinghat_allowed_hosts: "{{ groups['sortinghat'][0] }},{{ groups['mordred'][0] }}"
sortinghat_cors_allowed_origins: "https://{{ groups['sortinghat'][0] }},https://{{ groups['mordred'][0] }}"

# NGINX

sortinghat_host: "{{ inventory_hostname }}:9314"

## Image and container
nginx_docker_image: nginx
nginx_version: stable
nginx_docker_container: nginx

## Node configuration
nginx_workdir: "/docker/nginx"
nginx_virtualhosts_workdir: "{{ nginx_workdir }}/conf"

## Enable SSL
enable_ssl: False

## Certificates configuration. Only used if SSL is enabled
certs_dir: "{{ nginx_workdir }}/certs"

## Uncomment to define custom certificates. Otherwise self-signed
## certificates will be used. Only needed if SSL is enabled
# custom_cert:
#   cert: foo/cert.crt
#   key: foo/cert.key
